export const PLACEHOLDER_IMAGE_PATHS = {
  heroProductBox: '/images/placeholders/hero-product-box.png',
  firstNightBox: '/images/placeholders/first-night-box.png',
  anniversarySparkBox: '/images/placeholders/anniversary-spark-box.png',
  weekendEscapeBox: '/images/placeholders/weekend-escape-box.png',
  newlywedLuxuryKit: '/images/placeholders/newlywed-luxury-kit.png',
  coupleRitualsBox: '/images/placeholders/weekend-escape-box.png',
  afterDarkCardDeck: '/images/placeholders/anniversary-spark-box.png',
  firstDateNightKit: '/images/placeholders/first-night-box.png',
  honeymoonKit: '/images/placeholders/newlywed-luxury-kit.png',
  bridalIntimacyKit: '/images/placeholders/first-night-box.png',
  longDistanceReunionKit: '/images/placeholders/weekend-escape-box.png',
  babymoonKit: '/images/placeholders/newlywed-luxury-kit.png',
  couplePerfumes: '/images/placeholders/hero-product-box.png',
  personalisedGifts: '/images/placeholders/newlywed-luxury-kit.png',
  luxuryLetters: '/images/placeholders/anniversary-spark-box.png',
  instagram1: '/images/placeholders/hero-product-box.png',
  instagram2: '/images/placeholders/first-night-box.png',
  instagram3: '/images/placeholders/anniversary-spark-box.png',
  instagram4: '/images/placeholders/weekend-escape-box.png',
  instagram5: '/images/placeholders/newlywed-luxury-kit.png',
  instagram6: '/images/placeholders/hero-product-box.png',
} as const;

export type PlaceholderImageKey = keyof typeof PLACEHOLDER_IMAGE_PATHS;
